# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "sbenzarS"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "sbenKubernetes"
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - --flannel-iface=eth1
  kubectl apply -f /vagrant/manifests/app1.yaml >/dev/null 2>&1
  kubectl apply -f /vagrant/manifests/app2.yaml >/dev/null 2>&1
  kubectl apply -f /vagrant/manifests/app3.yaml >/dev/null 2>&1
  kubectl apply -f /vagrant/ingress.yaml >/dev/null 2>&1
  SHELL
end