# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "sbenzarS" do |sbenzarS|
    sbenzarS.vm.box = "centos/7"
    sbenzarS.vm.hostname = "sbenzarS"
    sbenzarS.vm.network :private_network, ip: "192.168.56.110", :netmask => "255.255.255.0"
    sbenzarS.vm.provider :virtualbox do |vb|
      vb.name = "sbenzarS"
      vb.memory = "512"
      vb.cpus = 1
    end
     sbenzarS.vm.provision "shell", inline: <<-SHELL
     curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - --flannel-iface=eth1
     sudo cat /var/lib/rancher/k3s/server/token > /home/vagrant/token
     SHELL
  end

  config.vm.define "sbenzarSW" do |sbenzarSW|
    sbenzarSW.vm.box = "centos/7"
    sbenzarSW.vm.hostname = "sbenzarSW"
    sbenzarSW.vm.network :private_network, ip: "192.168.56.111", :netmask => "255.255.255.0"
    sbenzarSW.vm.provider :virtualbox do |vb|
      vb.name = "sbenzarSW"
      vb.memory = "512"
      vb.cpus = 1
    end
  end
end
