# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "sbenzarS" do |sbenzarS|
    sbenzarS.vm.box = "centos/7"
    sbenzarS.vm.hostname = "sbenzarS"
    sbenzarS.vm.network :private_network, ip: "192.168.56.110"
    sbenzarS.vm.provider :virtualbox do |vb|
      vb.name = "sbenzarS"
      vb.memory = "512"
      vb.cpus = 1
    end
     sbenzarS.vm.provision "shell", inline: <<-SHELL
     curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - --flannel-iface=eth1
     # Get the node token from the server
    #  k3s_token=$(vagrant ssh sbenzarS sudo cat /var/lib/rancher/k3s/server/token)
     sudo cat /var/lib/rancher/k3s/server/token > /home/vagrant/token
     # get the node token from the server
      # NODE_TOKEN=$(sudo cat /var/lib/rancher/k3s/server/token)
     SHELL

    #  sbenzarS.trigger.after :up do |trigger|
    #   trigger.run = {inline: "vagrant scp sbenzarS:/vagrant/token ."}
    #  end
  end

  config.vm.define "sbenzarSW" do |sbenzarSW|
    sbenzarSW.vm.box = "centos/7"
    sbenzarSW.vm.hostname = "sbenzarSW"
    sbenzarSW.vm.network :private_network, ip: "192.168.56.111"
    sbenzarSW.vm.provider :virtualbox do |vb|
      vb.name = "sbenzarSW"
      vb.memory = "512"
      vb.cpus = 1
    end
    sbenzarSW.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/token) INSTALL_K3S_EXEC="--flannel-iface eth1" sh -s -
    SHELL

  end
end
# #!/bin/bash

# # Get the node token from the server
# token=$(ssh <k3s-server-ip> sudo cat /var/lib/rancher/k3s/server/node-token)

# # Join the worker to the server
# curl -sfL https://get.k3s.io | K3S_URL=https://<k3s-server-ip>:6443 K3S_TOKEN=$token sh -

# # Wait for the worker node to be ready
# while [[ $(ssh <k3s-server-ip> sudo kubectl get node | grep $(hostname) | awk '{print $2}') != "Ready" ]]; do sleep 1; done

# # Done
# echo "Worker joined k3s server successfully."
