apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: hello-from-app1
        image: paulbouwer/hello-kubernetes
        ports:
        - containerPort: 80